### PR TITLE
SLING-2938 - move integration tests here, using invoker plugin

### PR DESCRIPTION
**Pull request by bdelacretaz**
This PR uses maven-invoker-plugin to bring the integration tests in the same repository while keeping them isolated. I'll discuss at https://issues.apache.org/jira/browse/SLING-2938

### CODE REVIEW

**Comment by bdelacretaz** [comment]
The build checks have failed due to

> [INFO] [ERROR] org.apache.sling.adapter.annotations.AdapterRegistrationIT  Time elapsed: 63.218 s  <<< ERROR!
> [INFO] java.util.concurrent.TimeoutException: Call failed to return true in 60000 ms. Last exception was: null

I've seen this sporadically when running tests, it looks like the Sling instance setup does not work every time. 

Looks like that might be https://issues.apache.org/jira/browse/SLING-8080 as mentioned by Konrad at https://issues.apache.org/jira/browse/SLING-2938

_Update: I have committed a (hopeful) workaround for SLING-8080 to the PR, by explicitly adding the artifact versions in it-model.txt_

**Comment by henrykuijpers** [comment]
I'm very happy with these changes, @bdelacretaz! Looks very good to me. :) I'm also very glad that the SLING-8080 issue seems to be fixed now; This was worrying me a little bit. 

+1 from me to merge these changes and put out a release very soon.
(Unfortunately I do not have write access to the repository, so I can't do the merge.)

**Comment by kwin** [comment]
@bdelacretaz Can you create a PR for deprecating the dedicated IT repo: https://sling.apache.org/documentation/development/deprecating-sling-modules.html?

**Comment by bdelacretaz** [comment]
I have already deprecated the https://github.com/apache/sling-org-apache-sling-adapter-annotations-it/ module, hope that works for you @kwin ?

I have merged the PR discussed above and set https://github.com/apache/sling-org-apache-sling-adapter-annotations to build hourly to check if the ITs are stable (not 100% sure of my SLING-8080 workaround). 

I'll observe the tests for a bit a plan to make a release tomorrow if that works for others.

**Pull request merged**
